In [40]:
%pylab

ImportError: Matplotlib qt-based backends require an external PyQt4, PyQt5,
or PySide package to be installed, but it was not found.

In [33]:
import matplotlib
import pandas as pd


In [34]:
import numpy as np

In [35]:
print(numpy.__version__)

NameError: name 'numpy' is not defined

In [36]:
import matplotlib.pyplot as mat

In [37]:
%matplotlib inline

In [38]:
data=np.genfromtxt('phenotypes.csv',delimiter=',',skip_header=1)

In [39]:
print(data)

[[ nan   2.   1. ...,   3.   2.   1.]
 [ nan   1.   3. ...,   0.   2.   2.]
 [ nan   2.   1. ...,   0.   2.   2.]
 ..., 
 [ nan   1.   1. ...,   0.   2.   2.]
 [ nan   1.   1. ...,   1.   2.   1.]
 [ nan   1.   1. ...,   0.   2.   2.]]


In [26]:
print(len(data))

1139


In [14]:
print(data.shape)

(1139, 66)


In [15]:
print(type(data))

<class 'numpy.ndarray'>


In [16]:
name=data[:,0]

In [17]:
name

array([ nan,  nan,  nan, ...,  nan,  nan,  nan])

In [20]:
word_reading_ability=data[:,1]

In [21]:
word_reading_ability

array([ 2.,  1.,  2., ...,  1.,  1.,  1.])

In [32]:
smoking=data[:,9]

smoking

In [33]:
smoking

array([ 2.,  1.,  1., ...,  2.,  2.,  1.])

In [24]:
weight=data[:,3]

In [25]:
weight

array([ 1.,  2.,  2., ...,  2.,  0.,  1.])

In [18]:
vitaminE=data[:,4]

NameError: name 'data' is not defined

In [27]:
vitaminE

array([ 2.,  2.,  0., ...,  2.,  2.,  4.])

In [2]:
types = pd.read_csv('phenotypes.csv')

In [15]:
for i in range(types.weight.size):
    print("Person", i, " has weight ", types.weight[i])


Person 0  has weight  1
Person 1  has weight  2
Person 2  has weight  2
Person 3  has weight  2
Person 4  has weight  2
Person 5  has weight  1
Person 6  has weight  2
Person 7  has weight  3
Person 8  has weight  0
Person 9  has weight  1
Person 10  has weight  2
Person 11  has weight  3
Person 12  has weight  0
Person 13  has weight  2
Person 14  has weight  1
Person 15  has weight  2
Person 16  has weight  2
Person 17  has weight  2
Person 18  has weight  2
Person 19  has weight  2
Person 20  has weight  1
Person 21  has weight  2
Person 22  has weight  0
Person 23  has weight  2
Person 24  has weight  2
Person 25  has weight  2
Person 26  has weight  2
Person 27  has weight  2
Person 28  has weight  2
Person 29  has weight  1
Person 30  has weight  0
Person 31  has weight  1
Person 32  has weight  1
Person 33  has weight  1
Person 34  has weight  1
Person 35  has weight  1
Person 36  has weight  1
Person 37  has weight  1
Person 38  has weight  2
Person 39  has weight  0
Person 40 

In [16]:
protein_intake=data[:,17]

NameError: name 'data' is not defined

In [17]:
protein_intake

NameError: name 'protein_intake' is not defined

In [63]:
arrDataCol=[3,4,17]

In [64]:
arrDataCol[0]

3

In [65]:
for i in range(len(arrDataCol)):
    i=data[:,arrDataCol[i]]
    print(i)

[ 1.  2.  2. ...,  2.  0.  1.]
[ 2.  2.  0. ...,  2.  2.  4.]
[ 1.  1.  0. ...,  1.  0.  1.]


In [44]:
axis = {(0, 'weight')}

In [48]:
dfcum = types.cumsum()

In [61]:
lastindex = len(dfcum.weight) -1 
total = dfcum.weight[lastindex]
average = total/lastindex
print(average)

1.4718804920913884


In [55]:
len(dfcum.weight)


1139

In [ ]:
#Columns we should look for correlation between 
#depression, anger, openness, longevity, basically s

In [74]:
corrtest = types.corr()


In [77]:
corrtest.cumsum()

word-reading-ability  \
word-reading-ability                               1.000000   
white-wine-liking                                  0.798173   
weight                                             0.851410   
vitamin-e                                          0.819720   
vitamin-d                                          0.767531   
vitamin-b12                                        0.768753   
vitamin-a                                          0.680547   
type-2-diabetes                                         NaN   
smoking-behavior                                   0.721116   
smell-sensitivity-for-malt                         0.678543   
skin-pigmentation                                  0.672867   
reward-dependence                                  0.807974   
response-to-vitamin-e-supplementation              0.800630   
red-wine-liking                                    0.629276   
red-hair                                           0.696372   
reading-and-spelling-ability                       0.735796   
protein-intake                                     0.773722   
prostate-cancer                                         NaN   
phosphorus                                         0.828710   
peanuts-allergy                                    0.839153   
pancreatic-cancer                                       NaN   
openness                                           0.861436   
novelty-seeking                                    1.003179   
nicotine-dependence                                     NaN   
neuroticism                                        0.924810   
myocardial-infarction                                   NaN   
motion-sickness                                    0.972550   
morning-person                                     0.952503   
milk-allergy                                       0.808443   
male-pattern-baldness-aga                          0.720238   
...                                                     ...   
iron                                               0.738318   
hearing-function                                   0.751089   
harm-avoidance                                     0.740070   
handedness                                         0.826389   
gastric-cancer                                          NaN   
gambling                                           0.738852   
freckles                                           0.716395   
folate                                             0.732990   
eye-color                                          0.715784   
extraversion                                       0.705865   
endurance-performance                              0.677351   
egg-allergy                                        0.565899   
depression                                         0.533109   
conscientiousness                                  0.565584   
colorectal-cancer                                       NaN   
childhood-intelligence                             0.626298   
carbohydrate-intake                                0.534176   
calcium                                            0.466677   
caffeine-metabolite-ratio                          0.446637   
caffeine-consumption                               0.435639   
breast-cancer                                           NaN   
bmi                                                0.415360   
black-hair                                         0.459779   
bitter-taste                                       0.363723   
beta-carotene                                      0.335669   
beard-thickness                                    0.540603   
anger                                              0.486377   
alpha-linolenic-acid                               0.371232   
alcohol-drinking-behavior                               NaN   
agreeableness                                      0.336066   

                                       white-wine-liking    weight  vitamin-e  \
word-reading-ability                           -0.2