In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [3]:
import matplotlib


In [6]:
import numpy as np

In [5]:
print(numpy.__version__)

1.12.1


In [7]:
import matplotlib.pyplot as mat

In [8]:
%matplotlib inline

In [10]:
data=np.genfromtxt('phenotypes.csv',delimiter=',',skip_header=1)

In [11]:
print(data)

[[ nan   2.   1. ...,   3.   2.   1.]
 [ nan   1.   3. ...,   0.   2.   2.]
 [ nan   2.   1. ...,   0.   2.   2.]
 ..., 
 [ nan   1.   1. ...,   0.   2.   2.]
 [ nan   1.   1. ...,   1.   2.   1.]
 [ nan   1.   1. ...,   0.   2.   2.]]


In [13]:
print(len(data))

1139


In [14]:
print(data.shape)

(1139, 66)


In [15]:
print(type(data))

<class 'numpy.ndarray'>


In [16]:
name=data[:,0]

In [17]:
name

array([ nan,  nan,  nan, ...,  nan,  nan,  nan])

In [20]:
word_reading_ability=data[:,1]

In [21]:
word_reading_ability

array([ 2.,  1.,  2., ...,  1.,  1.,  1.])

In [32]:
smoking=data[:,9]

smoking

In [33]:
smoking

array([ 2.,  1.,  1., ...,  2.,  2.,  1.])

In [24]:
weight=data[:,3]

In [25]:
weight

array([ 1.,  2.,  2., ...,  2.,  0.,  1.])

In [26]:
vitaminE=data[:,4]

In [27]:
vitaminE

array([ 2.,  2.,  0., ...,  2.,  2.,  4.])

In [57]:
protein_intake=data[:,17]

In [58]:
protein_intake

array([ 1.,  1.,  0., ...,  1.,  0.,  1.])

In [63]:
arrDataCol=[3,4,17]

In [64]:
arrDataCol[0]

3

In [65]:
for i in range(len(arrDataCol)):
    i=data[:,arrDataCol[i]]
    print(i)

[ 1.  2.  2. ...,  2.  0.  1.]
[ 2.  2.  0. ...,  2.  2.  4.]
[ 1.  1.  0. ...,  1.  0.  1.]
