In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [1]:
import matplotlib
import pandas as pd


In [6]:
import numpy as np

In [5]:
print(numpy.__version__)

1.12.1


In [7]:
import matplotlib.pyplot as mat

In [8]:
%matplotlib inline

In [10]:
data=np.genfromtxt('phenotypes.csv',delimiter=',',skip_header=1)

In [11]:
print(data)

[[ nan   2.   1. ...,   3.   2.   1.]
 [ nan   1.   3. ...,   0.   2.   2.]
 [ nan   2.   1. ...,   0.   2.   2.]
 ..., 
 [ nan   1.   1. ...,   0.   2.   2.]
 [ nan   1.   1. ...,   1.   2.   1.]
 [ nan   1.   1. ...,   0.   2.   2.]]


In [13]:
print(len(data))

1139


In [14]:
print(data.shape)

(1139, 66)


In [15]:
print(type(data))

<class 'numpy.ndarray'>


In [16]:
name=data[:,0]

In [17]:
name

array([ nan,  nan,  nan, ...,  nan,  nan,  nan])

In [20]:
word_reading_ability=data[:,1]

In [21]:
word_reading_ability

array([ 2.,  1.,  2., ...,  1.,  1.,  1.])

In [32]:
smoking=data[:,9]

smoking

In [33]:
smoking

array([ 2.,  1.,  1., ...,  2.,  2.,  1.])

In [24]:
weight=data[:,3]

In [25]:
weight

array([ 1.,  2.,  2., ...,  2.,  0.,  1.])

In [26]:
vitaminE=data[:,4]

In [27]:
vitaminE

array([ 2.,  2.,  0., ...,  2.,  2.,  4.])

In [2]:
types = pd.read_csv('phenotypes.csv')

In [15]:
for i in range(types.weight.size):
    print("Person", i, " has weight ", types.weight[i])


Person 0  has weight  1
Person 1  has weight  2
Person 2  has weight  2
Person 3  has weight  2
Person 4  has weight  2
Person 5  has weight  1
Person 6  has weight  2
Person 7  has weight  3
Person 8  has weight  0
Person 9  has weight  1
Person 10  has weight  2
Person 11  has weight  3
Person 12  has weight  0
Person 13  has weight  2
Person 14  has weight  1
Person 15  has weight  2
Person 16  has weight  2
Person 17  has weight  2
Person 18  has weight  2
Person 19  has weight  2
Person 20  has weight  1
Person 21  has weight  2
Person 22  has weight  0
Person 23  has weight  2
Person 24  has weight  2
Person 25  has weight  2
Person 26  has weight  2
Person 27  has weight  2
Person 28  has weight  2
Person 29  has weight  1
Person 30  has weight  0
Person 31  has weight  1
Person 32  has weight  1
Person 33  has weight  1
Person 34  has weight  1
Person 35  has weight  1
Person 36  has weight  1
Person 37  has weight  1
Person 38  has weight  2
Person 39  has weight  0
Person 40 

In [11]:
protein_intake=data[:,17]

NameError: name 'data' is not defined

In [58]:
protein_intake

array([ 1.,  1.,  0., ...,  1.,  0.,  1.])

In [63]:
arrDataCol=[3,4,17]

In [64]:
arrDataCol[0]

3

In [65]:
for i in range(len(arrDataCol)):
    i=data[:,arrDataCol[i]]
    print(i)

[ 1.  2.  2. ...,  2.  0.  1.]
[ 2.  2.  0. ...,  2.  2.  4.]
[ 1.  1.  0. ...,  1.  0.  1.]
